# HTTP Server
[server]
	Address     = ":8199"
	ServerAgent = "rsshub"
	LogPath     = "/tmp/log/rsshub/server"

# Logger.
[logger]
    Path        = "/tmp/log/rsshub"
    Level       = "all"
    Stdout      = true

[redis]
host = "localhost:6379"
password = "123456"
db = 0