# HTTP Server
[server]
	Address     = ":8199"
	ServerAgent = "rsshub"
	LogPath     = "/tmp/log/rsshub/server"

# Logger.
[logger]
    Path        = "/tmp/log/rsshub"
    Level       = "all"
    Stdout      = true
