# HTTP Server
[server]
Address = ":8199"
ServerAgent = "rsshub"
LogPath = "/tmp/log/rsshub/server"

# Logger.
[logger]
Path = "/tmp/log/rsshub"
Level = "all"
Stdout = true

[redis]
default = "127.0.0.1:6379,0,123456?idleTimeout=600"

[cookies]
zhihu = ''
bilibili = ''

[database]
[[database.default]]
host = "127.0.0.1"
port = "3306"
user = "rsshub"
pass = "qazxsw"
name = "rssdb"
type = "mysql"
#role = "(可选)数据库主从角色(master/slave)，不使用应用层的主从机制请均设置为master"
#debug = "(可选)开启调试模式"
#prefix = "(可选)表名前缀"
#dryRun = "(可选)ORM空跑(只读不写)"
#charset = "(可选)数据库编码(如: utf8/gbk/gb2312)，一般设置为utf8"
#weight = "(可选)负载均衡权重，用于负载均衡控制，不使用应用层的负载均衡机制请置空"
#linkinfo = "(可选)自定义数据库链接信息，当该字段被设置值时，以上链接字段(Host,Port,User,Pass,Name)将失效，但是type必须有值"
#maxIdle = "(可选)连接池最大闲置的连接数"
#maxOpen = "(可选)连接池最大打开的连接数"
#maxLifetime = "(可选)连接对象可重复使用的时间长度"
#createdAt = "(可选)自动创建时间字段名称"
#updatedAt = "(可选)自动更新时间字段名称"
#deletedAt = "(可选)软删除时间字段名称"
#timeMaintainDisabled = "(可选)是否完全关闭时间更新特性，true时CreatedAt/UpdatedAt/DeletedAt都将失效"