# HTTP Server
[server]
Address = ":8081"
ServerAgent = "rsshub"
LogPath = "/tmp/log/rsshub/server"
DumpRouterMap = false

# Logger.
[logger]
Path = "/tmp/log/rsshub"
Level = "all"
Stdout = true
writerColorEnable = true

[redis]
default = "127.0.0.1:6379,0,123456?idleTimeout=600"

[cookies]
zhihu = ''
bilibili = ''

[gfcli]
[gfcli.build]
name = "rsshub"
arch = "amd64"
system = "linux"
mod = "none"
cgo = 0
pack = "config"
version = "v1.0.0"
output = "./bin"
extra = ""